#!/usr/bin/perl
# ---   *   ---   *   ---
# JOJ-AUVI
#
# Attempts conversion of
# DA::Matmk output
#
# i.e., compressing materials
# generated by auvi

# ---   *   ---   *   ---
# deps

package main;

  use v5.36.0;
  use strict;
  use warnings;

  use English qw(-no_match_vars);

  use lib $ENV{'ARPATH'}.'/lib/sys/';

  use Style;
  use Fmat;

  use lib $ENV{'ARPATH'}.'/lib/';
  use Lang::Def;

# ---   *   ---   *   ---
# info

  our $VERSION = v0.00.1;#b
  our $AUTHOR  = 'IBN-3DILA';

# ---   *   ---   *   ---

my @names=(@ARGV) ? @ARGV : 'PLANK_BOX_0000';
my $calls=[

  [qw(

    joj

    -sd ../.cache/auvi/material/
    -o ../.cache/auvi/material/$:name;>
    -as 128

    $:name;>

  )],

  [qw(

    unjoj

    -o ../.cache/auvi/material/$:name;>_u
    ../.cache/auvi/material/$:name;>

  )],

];

# ---   *   ---   *   ---
# ^replace $:name;> with value

sub name_subst($v,$line) {
  $line=~ s[$PESC_RE][$v]sxmg;
  return $line;

};

# ---   *   ---   *   ---
# ^iter

for my $name(@names) {

  my @joj=map {
    name_subst($name,$ARG)

  } @{$calls->[0]};

  my @unjoj=map {
    name_subst($name,$ARG)

  } @{$calls->[1]};

  system {$joj[0]}   @joj;
  system {$unjoj[0]} @unjoj;

};

# ---   *   ---   *   ---
1; # ret
