# KVRNEL GNU MAKEFILE

#   ---     ---     ---     ---     ---
# module data

FSWAT     = KVRNEL
MKWAT     = kvrnel.dll

-include ../mkvars

LMODE     = -shared

LFLG     += -fPIC
LIBS     += 

-include ../mkrcee
