# SIN GNU MAKEFILE

#   ---     ---     ---     ---     ---
# module data

FSWAT     = SIN
MKWAT     = sin.dll

-include ../mkvars

LMODE     = -shared

LFLG     += -fPIC
LIBS     += -lkvrnel -lgl -lglew -lopengl32

-include ../mkrcee