#!/usr/bin/perl

#***************************
# AVTOMAT                  *
# build helper             *
# header generator stuff   *
#                          *
# LIBRE SOFTWARE           *
# Licensed under GNU GPL3  *
# be a bro and inherit     *
#                          *
# CONTRIBUTORS             *
# lyeb,                    *
#***************************

package AVTO;
use Time::Piece;

#    ---     ---     ---     ---     ---

sub mknot {

  my $t=Time::Piece->new();
  my $year_part=($t->year)." *";

  my $pstr=<<EOF
//**************************
// LIBRE BOILERPASTE       *
// GENERATED BY ES-AVTOMAT *
//                         *
// LICENSED UNDER GNU GPL3 *
// BE A BRO AND INHERIT    *
//                         *
// COPYLEFT IBN-3DILA $year_part
//**************************
EOF
;

  return $pstr;

};


sub mkdep {

  my $fname=@_[0];
  my $trsh=@_[1];
  my $s=<<EOF

$trsh/$fname.o: \$(CURDIR)/$fname.c \$(TRSH)/MKLOG
	\@gcc -MMD \$(OFLG) \$(INCLUDES) \$(DFLG) \$(PFLG) -Wa,-a=\$(subst .o,.asm,\$@) -c \$< -o \$@

$trsh/$fname.pch: \$(CURDIR)/$fname.h \$(TRSH)/MKLOG
	\@gcc \$(OFLG) \$(INCLUDES) \$(DFLG) \$(PFLG) -Wa,-a=\$(subst .pch,.h_asm,\$@) -x c -c \$< -o \$@

EOF
;

  return $s;

};

#    ---     ---     ---     ---     ---

package main;
$KVR_DEBUG="0xFFFF";

#   ---     ---     ---     ---     ---