/*/************************************************
 * LIBRE BOILERPASTE GENERATED BY ES-AVTOMAT      *
 * LICENSED UNDER GNU GPL3 : BE A BRO AND INHERIT *
 * COPYLEFT (c) CIXXPAKK 2021             *
 **************************************************/

#if KVR_DEBUG & KVR_CALOM
#define CALOUT_M(format, ...) __calout('M', format, ##__VA_ARGS__)
#else
#define CALOUT_M(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOF
#define CALOUT_F(format, ...) __calout('F', format, ##__VA_ARGS__)
#else
#define CALOUT_F(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOK
#define CALOUT_K(format, ...) __calout('K', format, ##__VA_ARGS__)
#else
#define CALOUT_K(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOE
#define CALOUT_E(format, ...) __calout('E', format, ##__VA_ARGS__)
#else
#define CALOUT_E(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOR
#define CALOUT_R(format, ...) __calout('R', format, ##__VA_ARGS__)
#else
#define CALOUT_R(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOH
#define CALOUT_H(format, ...) __calout('H', format, ##__VA_ARGS__)
#else
#define CALOUT_H(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOP
#define CALOUT_P(format, ...) __calout('P', format, ##__VA_ARGS__)
#else
#define CALOUT_P(format, ...) asm("nop")
#endif
#if KVR_DEBUG & KVR_CALOS
#define CALOUT_S(format, ...) __calout('S', format, ##__VA_ARGS__)
#else
#define CALOUT_S(format, ...) asm("nop")
#endif
#define CALOUT(fam, format, ...) CALOUT_##fam(format, ##__VA_ARGS__)

