# MAMMOTH GNU MAKEFILE

#   ---     ---     ---     ---     ---
# module data

FSWAT     = MAMMOTH
MKWAT     = mamm

-include ../mkvars

LMODE     = 

LFLG     += 
LIBS     += -lkvrnel

-include ../mkrcee