# SHB7 GNU MAKEFILE

#   ---     ---     ---     ---     ---
# module data

FSWAT     = SHB7
MKWAT     = shb7

-include ../mkvars

LMODE     = 

LFLG     += 
LIBS     += -lkvrnel -lgl -lglew -lopengl32 -lsin \
            -lSDL2main -lSDL2 -lchasm

-include ../mkrcee