# CHASM GNU MAKEFILE

#   ---     ---     ---     ---     ---
# module data

FSWAT     = CHASM
MKWAT     = chasm.dll

-include ../mkvars

LMODE     = -shared

LFLG     += -fPIC
LIBS     += -lkvrnel -lgl -lglew -lopengl32 \
            -lsin -lSDL2main -lSDL2

-include ../mkrcee